site_name: MkDocs Macros YAML Examples
site_description: An example site to demo using mkdocs-macros-plugin with YAML to generate content.
site_author: Deborah Barnard
docs_dir: src
site_dir: docs
theme:
  name: material
  features:
    - navigation.sections
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
  # Enable https://github.com/fralau/mkdocs_macros_plugin
  - macros:
      include_yaml:
        - _yaml/simple-example.yml
extra:
  extraValueOne: 1
  extraValueTwo: two
nav:
 - Home: index.md
 - Setup:
    - Clone and run: clone-run.md
    - Avoid clashing with code examples: clashing-code.md
    - List available variables: macros-info.md
 - YAML sources:
    - Frontmatter: frontmatter.md
    - MkDocs file: mkdocs-file.md
    - External YAML files: external-yaml-files.md 
    