site_name: MkDocs Examples and Tests
site_description: An example site to test out MkDocs and the Material theme.
site_author: Deborah Barnard
site_url: https://starfallprojects.github.io/mkdocs-examples-tests/
repo_url: https://github.com/StarfallProjects/mkdocs-examples-tests
theme:
  name: material
nav:
 - Home: index.md
    
